"""Add sender column to journal_entries

Revision ID: 5fbf973da006
Revises: fa45f9e1dc15
Create Date: 2025-09-12 15:56:47.842522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbf973da006'
down_revision: Union[str, Sequence[str], None] = 'fa45f9e1dc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('sender', sa.String(length=10), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'sender')
    # ### end Alembic commands ###
