# Generated by Django 5.2.3 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
