# Generated by Django 5.2.3 on 2025-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_journalentry_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=10),
        ),
    ]
